services:
  postgres:
    container_name: postgres_container
    image: postgres:15.3
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "SocialOtus"
      POSTGRES_USER: "otuspg"
      POSTGRES_PASSWORD: "learn4otus"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/initsql:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otuspg -d SocialOtus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - otuslab

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "no@mail.loc"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin4otus"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - otuslab

  labapp:
    container_name: otuslab_social
    build: .
    ports: 
      - "80:8080"
    environment:
      APP_M_DBHOST: 'postgres'
      APP_M_DBNAME: 'SocialOtus'
      APP_M_DBUSER: 'otuspg'
      APP_M_DBPWD: 'learn4otus'
      APP_M_CHOST: 'tl_cache'
      APP_M_CPORT: 3301
      APP_M_CUSER: 'otuspg'
      APP_M_CPWD: 'learn4otus'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - otuslab

  tarantool_cache:
    container_name: tl_cache
    image: tarantool/tarantool:2.10.8
    command: tarantool /usr/local/share/tarantool/cache.init.lua
    volumes:
      - ./db/tarantool_app:/usr/local/share/tarantool
      - ./db/tarantool_cache/lib:/var/lib/tarantool
      - ./db/tarantool_cache/log:/var/log/tarantool
    networks:
      - otuslab
    ports:
      - "3301:3301"
    depends_on:
      postgres:
        condition: service_healthy


networks:
  otuslab:
    driver: bridge