services:
  postgres:
    container_name: postgres_container
    image: postgres:15.3
    environment:
      POSTGRES_DB: "SocialOtus"
      POSTGRES_USER: "otuspg"
      POSTGRES_PASSWORD: "learn4otus"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/initsql:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otuspg -d SocialOtus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - otuslab

  labapp:
    container_name: otuslab_social
    build: .
    ports: 
      - "80:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - otuslab  

networks:
  otuslab:
    driver: bridge